### ISSUE TITLE
Invalid label specifier 

### ISSUE THREAD

**Issue by sBwatts** [aarondwolf/wrap#1]
Hello,

I'm trying to get variable labels to wrap for some basic distribution plots and I continue to get the same error. Here is my current code using two different approaches:
```
wrap truleo2_6, at(30)
violinplot truleo2_6, vertical ylab(`r(varlab)')

wrap "The Truleo system will allow the department to publicize good work."
violinplot truleo2_6, vertical ylab(`r(name)')
```

The two examples above provide me with the same error:
```
invalid label specifier, :  "The Truleo system will allow the"  "department to publicize good work.":
r(198);

end of do-file

r(198);
```
Any thoughts are appreciated. Thanks.

**Comment by aarondwolf** [comment]
Hi there! I am not very familiar with `violinplot`, but the documentation indicates you can pass any `twoway_options` to the command, and they will be passed to `twoway`. As such, if you are using `ylab`, this is actually passing `ylab` directly to `twoway`. If this is correct, then simply providing a string is not a valid `ylabel`: You need a value-string pair(s). perhaps you were looking to change the `ytitle` instead? Please let me know if I have this wrong and I can probe further.

**Comment by sBwatts** [comment]
Ah! `ytitle` did the trick. Sorry for the inconvenience, thanks!

**Comment by aarondwolf** [comment]
Great! I am marking this issue as closed.
